version: "3.9"

services:
  app:
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
    volumes:
      # プロジェクト全体を /workspace にマウント
      - ..:/workspace:cached
    working_dir: /workspace
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ../src:/workspace/src
      - ../docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
