FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    nginx \
    git unzip libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

COPY . .

RUN composer install --no-dev --optimize-autoloader

RUN chown -R www-data:www-data storage bootstrap/cache

# nginx設定
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Cloud Runは8080必須
EXPOSE 8080

# 起動（重要）
CMD ["sh", "-c", "php-fpm & nginx -g 'daemon off;'"]